
settings { 
	logfile = "_INSTALL_DIRECTORY/var/log/lsyncd.log", statusFile = "_INSTALL_DIRECTORY/var/log/lsyncd.status",
	insist = 1,
	maxDelays = 200
}

sync {
		default.rsync,
		source="{SERVER_WEBROOT}",
		target="rsync://_USER@_MIRROR_SERVER_IP/name",
		delay={DELAY},
                delete='running',
		exclude = {
		  "lsyncd/",
		  "{LSYNCD_TMP}"
		},
			rsync = {
			        archive  = true,
			        compress = true,
			        update = true,
				_extra = {
					"--port=7755","--password-file=_INSTALL_DIRECTORY/etc/rsyncd.pass", "--temp-dir=/"
				},
			}
		}
