uid = apache
max connections = 128
pid file = _INSTALL_DIRECTORY/var/run/rsyncd.pid
log file = _INSTALL_DIRECTORY/var/rsync.log
lock file = _INSTALL_DIRECTORY/var/rsync.lock
use chroot = no

[_NAME]
		path = {SERVER_WEBROOT}
		comment = Content sync
		auth users = _USER
		secrets file = _INSTALL_DIRECTORY/etc/rsyncd.secrets
		list = yes
		read only = no
		munge symlinks = no
